project_name: sherlock
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
dockers:
- image_templates: ["ghcr.io/jwillker/sherlock:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/jwillker/sherlock
  - --label=org.opencontainers.image.source=https://github.com/jwillker/sherlock
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
nfpms:
- maintainer: Jhonn Frazão <frazao.jhonn@gmail.com>
  description: A tool to search and index Golang projetcs in Sally vanity config.
  homepage: https://github.com/jwillker/sherlock
  license: MIT
  formats:
  - deb
  - rpm
  - apk
